name: "Notify on release"

env:
  TELEGRAM_CHANNEL: '@mphamzzz_channel' # Configure the Telegram channel
  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }} # Configure the Telegram bot token


on:
  release:
    types:
      - released
  workflow_run:
    workflows:
      - "Pre-release on push"
    branches:
      - main
    types:
      - completed

jobs:
  notify:
    name: "Notify on Telegram"
    runs-on: ubuntu-latest


    steps:

    - name: Checkout
      uses: actions/checkout@v2

    # Notify on Telegram channel
    - name: Telegram announcement
      run: |
        curl -G \
        --data-urlencode "chat_id=$TELEGRAM_CHANNEL" \
        --data-urlencode "text=Version $GITHUB_REF_NAME released! https://github.com/$GITHUB_REPOSITORY/releases/tag/$GITHUB_REF_NAME" \
        https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage

